publish workflow for github actions
civic-jabber/data-ingest pull request #17
Opened 2020-12-06 20:02 UTC by kvnkho

I know the initial issue said on tag creation but it seems people do it on releases. Do we need it on tags? Releases seem appropriate.

Not quite sure how to test this without publishing to PyPi

2020-12-06 20:18 UTC, MthwRobinson commented
@kvnkho -- Releases work for me. I'll test this locally using the PyPI creds a little later.

2020-12-06 20:53 UTC, MthwRobinson requested changes
There are a couple of other packaging items that I think we should hit in this PR.

1. `setup.py` doesn't install the dependencies right. We should have it install the  reqs in `requirements/base.txt`
1. Let's change the package name from `data_ingest` to `civic_jabber_ingest`. This command from the root directory of the project should (hopefully) do the trick: `find ./ -type f -exec sed -i -e 's/data_ingest/civic_jabber_ingest/g' {} \;

2020-12-06 20:53 UTC, MthwRobinson commented on .github/workflows/publish.yml
> +        twine upload dist/*
Do you want to add a `make publish` that runs `make package` and then runs `twine upload dist/*` after? Then I can give that a whirl locally with the twine environmental variables set.

2020-12-06 20:53 UTC, MthwRobinson commented on .github/workflows/publish.yml
> +        pip install setuptools wheel twine
We can probably add these to the dev dependencies. You can add them to `requirements/dev.in` and then run `make pip-compile`.

2020-12-06 23:49 UTC, kvnkho commented
i believe this is done.

aside from comments above, i also added init.py files for the setup.py to capture these modules when it calls find_packages().

2020-12-07 00:18 UTC, MthwRobinson commented
Thanks! One final comment for `setup.py` - I think we also need to add [package data](https://setuptools.readthedocs.io/en/latest/userguide/datafiles.html) to include the config `.yml` files and the Jinja templates in the build. Could you add that in as well?

2020-12-07 00:57 UTC, kvnkho commented
Added data files and tested. They are now present in wheel file.

2020-12-07 01:11 UTC, MthwRobinson approved these changes

2020-12-07 01:11 UTC, MthwRobinson commented
Working for me locally. LGTM. Thanks!! :-)

2020-12-07 01:19 UTC, merged